### ISSUE TITLE
Regression bug in LDAP functionality

### ISSUE THREAD

**Issue by nyholmju** [ICS-MU/pam_oauth2_device#27] opened 2021-08-18 14:42 UTC
Hi,

we noticed that ldap binds stopped working after commit https://github.com/ICS-MU/pam_oauth2_device/commit/019f24b6d720953ec9d60348528cd28676a33f55

passwd_local = (char *)malloc(sizeof(passwd));
sizeof(passwd) seems to cap the password length at 7 characters, so ldap credentials which use passwords that are longer than 7 characters fail to bind to ldap (invalid credentials).

There might also be a similar problem with ldap filter:
config->ldap_filter.length() + sizeof(username_remote);

Best regards,

Juha Nyholm

**Comment by jsurkont** [comment] 2021-08-24 13:12
Hi Juha.

Thanks for a detailed bug report. The problem here is incorrect char array calculation. I've now refactored the code to be more C++-like and changed how array size is calculated.

I tested the changes locally, but unfortunately, I don't have access to an LDAP server so I couldn't run the full test. It would be great if you could try the [fix-ldap-regression](https://github.com/ICS-MU/pam_oauth2_device/tree/fix-ldap-regression) branch. If it works as expected we can merge it to master.

Best,
Jaroslaw

**Comment by nyholmju** [comment] 2021-08-25 08:03
Hi Jaroslaw,

Thanks for the fix. I have tested the fix locally with our LDAP servers and it works as expected after you remove the following line https://github.com/ICS-MU/pam_oauth2_device/blob/037dbed720863b10678ab6c0dd3cd6060d434589/src/pam_oauth2_device.cpp#L399

Best regards,

Juha Nyholm

**Comment by jsurkont** [comment] 2021-08-25 11:42
Thanks for testing!

It's very strange that you need to delete this line. I would be reluctant to remove the line, since the memory used by the buffer should be freed when it's no longer used. In the line above, the content of the buffer is copied to a string, so it should be safe to free the memory. Locally, I can see that the value of `username_local` is correct in `ldapquery.cpp`. Could verify the value of the variable? You could add `syslog(LOG_INFO, "username_local: %s", value.c_str());` at the beginning of `ldap_check_attr` (you also need to add an include line `#include <syslog.h>`).

Maybe the difference is caused by the compiler version. For the reference I'm using `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

**Comment by nyholmju** [comment] 2021-08-25 12:12
Hi,

I suspect subsequent pam modules will need the username information. If you clear the buffer, then this information is not available for the next pam module(s)?

Error from syslog when delete is present in the code:
Aug 25 07:31:54 <hostname> pam_oauth2_device[2365]: user <my_username> mapped to <my_username> via LDAP
Aug 25 07:31:54 <hostname> pam_oauth2_device[2365]: authentication succeeded: <my_username> -> <my_username> 
Aug 25 07:31:55 <hostname>  sshd[2365]: pam_unix(sshd:account): could not identify user (from getpwnam(oid_section))
Aug 25 07:31:55 <hostname> sshd[2365]: pam_sss(sshd:account): Access denied for user oid_section: 10 (User not known to the underlying authentication module)

My username is not 'oid_section' :) Subsequent pam modules seem to use something random for username when buffer is deleted?

If I comment out delete[] buffer in the code, I am able to log in and pam_unix and pam_sss errors are no longer present in syslog.

BR, Juha

**Comment by jsurkont** [comment] 2021-08-25 13:05
Hi,

I didn't expect that, but I think you're right. I've removed the delete statement and added a comment to make sure it's not deleted in the future.

I've created a PR. Once reviewed it will be merged to master.

Thanks again for reporting the issue and testing the fix.

Best,
Jarosław

**Closed as completed** 2022-04-28 22:21 UTC
Labels: bug
